# This file was generated by GoReleaser. DO NOT EDIT.
cask "qube" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "e196aff5acaa0c07bc00049f423cdfc98b0f995c41f556e4a3c3d3e787ba7659"
      url "https://github.com/qubeintegrations/qube-cli/releases/download/v#{version}/qube_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8dc13013d61544a27c15592482bcb99fb6528206241455c89bd8f542d07b3459"
      url "https://github.com/qubeintegrations/qube-cli/releases/download/v#{version}/qube_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b16ff72226ab955437d67fcb1c080da79b2e234bc1efcec229a04ebbf88f37b2"
      url "https://github.com/qubeintegrations/qube-cli/releases/download/v#{version}/qube_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eabd1765a672516fce5484dc37cb940dfca81d2386072efa31bef8038084cee1"
      url "https://github.com/qubeintegrations/qube-cli/releases/download/v#{version}/qube_#{version}_linux_amd64.tar.gz"
    end
  end

  name "qube"
  desc "The QuBe Sync command line"
  homepage "https://qubesync.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qube"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qube"]
    end
  end

  # No zap stanza required
end
