# This file was generated by GoReleaser. DO NOT EDIT.
cask "qube" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "cb813a1127f4c6048788d3cfcbb13ea43d4bba47cc4feb89c8fe73c963fc8295"
      url "https://github.com/qubeintegrations/qube-cli/releases/download/v#{version}/qube_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5ece4c8fcf398b9631572690d2367f4d7605ed22c82f67d915e2fd5939a9f086"
      url "https://github.com/qubeintegrations/qube-cli/releases/download/v#{version}/qube_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1d55f2d9253625279549897b5f6cf4ad5de738e33ef4ed1be748aa0c87b12380"
      url "https://github.com/qubeintegrations/qube-cli/releases/download/v#{version}/qube_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c34fd26469bc62822593d1a474430fd6e1d2fb6764eaebaa9866d0fd48c196a5"
      url "https://github.com/qubeintegrations/qube-cli/releases/download/v#{version}/qube_#{version}_linux_amd64.tar.gz"
    end
  end

  name "qube"
  desc "The QuBe Sync command line"
  homepage "https://qubesync.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qube"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qube"]
    end
  end

  # No zap stanza required
end
