# This file was generated by GoReleaser. DO NOT EDIT.
cask "qube" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "qube"], chdir: ".", must_succeed: false
  end

  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "ced12d6654b347be195a3263fef8aac26ba95d039af6bb08b53bcbd290227653"
      url "https://github.com/qubeintegrations/qube-cli/releases/download/v#{version}/qube_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a7e820ab49e30397e2a6cca68acceb68e14eb09fd4a2f7263dd8b4ee6c84bba6"
      url "https://github.com/qubeintegrations/qube-cli/releases/download/v#{version}/qube_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ed0e36025ce64799e291af3f352333e82a30dc817167f5e78a7c7b88e38704b5"
      url "https://github.com/qubeintegrations/qube-cli/releases/download/v#{version}/qube_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "88912ea506f119ba5e178c1028a699561214f990d22e0a32c818f552aa92ff07"
      url "https://github.com/qubeintegrations/qube-cli/releases/download/v#{version}/qube_#{version}_linux_amd64.tar.gz"
    end
  end

  name "qube"
  desc "The QuBe Sync command line"
  homepage "https://qubesync.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qube"

  # No zap stanza required
end
